# Generated by Django 4.0.6 on 2022-07-27 12:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('parentID', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('type', models.CharField(choices=[('OFFER', 'Offer'), ('CATEGORY', 'Category')], max_length=10)),
                ('price', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
