# Generated by Django 4.0.6 on 2022-07-27 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField()),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopUnitImport',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('parentID', models.UUIDField(editable=False, null=True)),
                ('type', models.CharField(choices=[('OFFER', 'Offer'), ('CATEGORY', 'Category')], max_length=10)),
                ('price', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopUnitStatisticUnit',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('parentID', models.UUIDField(editable=False, null=True)),
                ('type', models.CharField(choices=[('OFFER', 'Offer'), ('CATEGORY', 'Category')], max_length=10)),
                ('price', models.PositiveIntegerField(null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='shopunit',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ShopUnitStatisticResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega_market.shopunitstatisticunit')),
            ],
        ),
        migrations.CreateModel(
            name='ShopUnitImportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateDate', models.DateField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega_market.shopunitimport')),
            ],
        ),
    ]
