# Generated by Django 4.0.6 on 2022-07-31 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0002_error_shopunitimport_shopunitstatisticunit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='parentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mega_market.shopunit'),
        ),
    ]
