# Generated by Django 4.0.6 on 2022-07-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0004_alter_shopunit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
