# Generated by Django 4.0.6 on 2022-07-31 14:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0005_alter_shopunit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunitimport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shopunitimport',
            name='parentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mega_market.shopunit'),
        ),
        migrations.AlterField(
            model_name='shopunitstatisticunit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shopunitstatisticunit',
            name='parentID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
