# Generated by Django 4.0.6 on 2022-07-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0006_alter_shopunitimport_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shopunitimportrequest',
            name='updateDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shopunitstatisticunit',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
