# Generated by Django 4.0.6 on 2022-08-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0007_alter_shopunit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunitimport',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='ShopUnitImportRequest',
        ),
    ]
