# Generated by Django 4.0.6 on 2022-08-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0008_alter_shopunitimport_id_delete_shopunitimportrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnitImportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updateDate', models.DateField()),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mega_market.shopunitimport')),
            ],
        ),
    ]
