# Generated by Django 4.0.6 on 2022-08-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0009_shopunitimportrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunitimportrequest',
            name='updateDate',
            field=models.DateTimeField(),
        ),
    ]
