# Generated by Django 4.0.6 on 2022-08-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0010_alter_shopunitimportrequest_updatedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
