# Generated by Django 4.0.6 on 2022-08-07 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0011_alter_shopunit_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopunit',
            old_name='parentID',
            new_name='parentId',
        ),
    ]
