# Generated by Django 4.0.6 on 2022-08-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mega_market', '0013_alter_shopunit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopunit',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
